openapi: 3.0.0
info:
  title: API Template
  version: 1.0.0
paths:
  /api/v1/auth/login:
    post:
      summary: Login a user
      description: Authenticate user and return JWT
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: supersecure123
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      fname:
                        type: string
                      lname:
                        type: string
        401:
          description: Invalid credentials

  /api/v1/auth/me:
    get:
      summary: Return the authenticated user's payload
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        200:
          description: Authenticated user payload
        401:
          description: Missing or invalid token
        403:
          description: Invalid or expired token
