openapi: 3.0.0
info:
  title: API Template
  version: 1.0.0
paths:
  /api/v1/health:
    get:
      summary: Check API and database health status
      description: Returns the API uptime and database connection status.
      tags:
        - Health
      responses:
        200:
          description: API is running and database is connected
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  uptime:
                    type: number
                    example: 123.45
                  database:
                    type: string
                    example: connected
                  timestamp:
                    type: number
                    example: 1682219912345
        500:
          description: Database connection failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  database:
                    type: string
                    example: disconnected
                  error:
                    type: string
                    example: Unable to connect to the database.
