# docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_dev
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
